// <auto-generated />
namespace dot_not.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FlagsHaveNoTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FlagsHaveNoTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201611211624315_FlagsHaveNoTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
